export default [
  {
    id: 1,
    img: "card1.svg",
    rating: "5.0",
    reviewCount: 6,
    country: "USA",
    title: "Life lessons with Katie Zaferes",
    price: 136,
    openSpots: 0,
    location: "Online",
  },
  {
    id: 2,
    img: "card2.svg",
    rating: "5.0",
    reviewCount: 30,
    country: "USA",
    title: "Learn wedding photography",
    price: 125,
    openSpots: 27,
    location: "Online",
  },
  {
    id: 3,
    img: "card3.svg",
    rating: "4.8",
    reviewCount: 2,
    country: "USA",
    title: "Group Mountain Biking",
    price: 50,
    openSpots: 3,
    location: "Norway",
  },
];
